[
  {
    "arguments": [
      "/usr/bin/gcc",
      "-Os",
      "-mtune=native",
      "-fno-exceptions",
      "-Wall",
      "-Wextra",
      "-Wmissing-prototypes",
      "-Wdiv-by-zero",
      "-Wbad-function-cast",
      "-Wcast-align",
      "-Wcast-qual",
      "-Wfloat-equal",
      "-Wmissing-declarations",
      "-Wnested-externs",
      "-Wno-unknown-pragmas",
      "-Wpointer-arith",
      "-Wredundant-decls",
      "-Wstrict-prototypes",
      "-Wswitch-enum",
      "-Wno-type-limits",
      "-I.",
      "-c",
      "-o",
      "hydrogen.o",
      "hydrogen.c"
    ],
    "directory": "ROOT/cydrogen/src",
    "file": "hydrogen.c",
    "output": "hydrogen.o"
  },
  {
    "arguments": [
      "/usr/bin/gcc",
      "-DHAVE_STDIO_H=1",
      "-DHAVE_STDLIB_H=1",
      "-DHAVE_STRING_H=1",
      "-DHAVE_INTTYPES_H=1",
      "-DHAVE_STDINT_H=1",
      "-DHAVE_STRINGS_H=1",
      "-DHAVE_SYS_STAT_H=1",
      "-DHAVE_SYS_TYPES_H=1",
      "-DHAVE_UNISTD_H=1",
      "-DHAVE_WCHAR_H=1",
      "-DHAVE_C_VARARRAYS=1",
      "-DHAVE_DLFCN_H=1",
      "-DHAVE_SYS_MMAN_H=1",
      "-DHAVE_SYS_PARAM_H=1",
      "-DHAVE_SYS_RANDOM_H=1",
      "-DHAVE_SYS_AUXV_H=1",
      "-DNATIVE_LITTLE_ENDIAN=1",
      "-DHAVE_WEAK_SYMBOLS=1",
      "-DHAVE_ALLOCA_H=1",
      "-DHAVE_ALLOCA=1",
      "-DHAVE_MMAP=1",
      "-DHAVE_MLOCK=1",
      "-DHAVE_MADVISE=1",
      "-DHAVE_MPROTECT=1",
      "-DHAVE_RAISE=1",
      "-DHAVE_POSIX_MEMALIGN=1",
      "-DHAVE_EXPLICIT_BZERO=1",
      "-I.",
      "-Os",
      "-fno-strict-aliasing",
      "-fno-strict-overflow",
      "-fstack-protector",
      "-Wno-deprecated-declarations",
      "-Wno-unknown-pragmas",
      "-c",
      "-o",
      "cyutils.o",
      "cyutils.c"
    ],
    "directory": "ROOT/cydrogen",
    "file": "cyutils.c",
    "output": "cyutils.o"
  },
  {
    "arguments": [
      "/usr/bin/gcc",
      "-DHAVE_STDIO_H=1",
      "-DHAVE_STDLIB_H=1",
      "-DHAVE_STRING_H=1",
      "-DHAVE_INTTYPES_H=1",
      "-DHAVE_STDINT_H=1",
      "-DHAVE_STRINGS_H=1",
      "-DHAVE_SYS_STAT_H=1",
      "-DHAVE_SYS_TYPES_H=1",
      "-DHAVE_UNISTD_H=1",
      "-DHAVE_WCHAR_H=1",
      "-DHAVE_C_VARARRAYS=1",
      "-DHAVE_DLFCN_H=1",
      "-DHAVE_SYS_MMAN_H=1",
      "-DHAVE_SYS_PARAM_H=1",
      "-DHAVE_SYS_RANDOM_H=1",
      "-DHAVE_SYS_AUXV_H=1",
      "-DNATIVE_LITTLE_ENDIAN=1",
      "-DHAVE_WEAK_SYMBOLS=1",
      "-DHAVE_ALLOCA_H=1",
      "-DHAVE_ALLOCA=1",
      "-DHAVE_MMAP=1",
      "-DHAVE_MLOCK=1",
      "-DHAVE_MADVISE=1",
      "-DHAVE_MPROTECT=1",
      "-DHAVE_RAISE=1",
      "-DHAVE_POSIX_MEMALIGN=1",
      "-DHAVE_EXPLICIT_BZERO=1",
      "-I.",
      "-Os",
      "-fno-strict-aliasing",
      "-fno-strict-overflow",
      "-fstack-protector",
      "-Wno-deprecated-declarations",
      "-Wno-unknown-pragmas",
      "-c",
      "-o",
      "cyd_memcpy_s.o",
      "cyd_memcpy_s.c"
    ],
    "directory": "ROOT/cydrogen",
    "file": "cyd_memcpy_s.c",
    "output": "cyd_memcpy_s.o"
  }
]
