[build-system]
build-backend = "mesonpy"

requires = ["meson-python >= 0.18.0", "cython >= 3.1.2"]

[project]
name = "cydrogen"
version = "0.0.11-dev"
description = "Cython bindings for the libhydrogen library"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
classifiers = [
  # Complete classifiers list is available here: https://pypi.org/classifiers/
  "Development Status :: 3 - Alpha",
  # "Development Status :: 4 - Beta",
  # "Development Status :: 5 - Production/Stable",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  # Specify the Python versions you support here.
  # These classifiers are *not* checked by 'pip install'. See instead
  # 'requires-python'.
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Cython",
  "Programming Language :: Python :: Implementation :: CPython",
  # others
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Software Development :: Libraries",
  "Topic :: Security :: Cryptography",
]

[project.urls]
Homepage = "https://cydrogen.readthedocs.io"
Documentation = "https://cydrogen.readthedocs.io"
Repository = "https://github.com/stephane-martin/cydrogen"
Issues = "https://github.com/stephane-martin/cydrogen/issues"
Changelog = "https://github.com/stephane-martin/cydrogen/blob/develop/CHANGELOG.md"

[dependency-groups]

develop = [
  "meson>=1.8.2",
  "meson-python>=0.18.0",
  "nox",
  "pre-commit",
  "pip-audit",
  "pip-tools",
  "tomlkit>=0.13.2",
  "semver>=3.0.0,<4",
]

lint = [
  "ruff>=0.11.10",
  "mypy>=1.15.0",
  "mypy-extensions>=1.1.0",
  "cython-lint>=0.16.6",
  "zizmor",
  "pytest>=8.3.5",
  "pytest-asyncio>=1.0.0",
]

build = ["build>=0.11.0", "twine"]

test = ["build>=0.11.0", "pytest>=8.3.5", "pytest-asyncio>=1.0.0"]

docs = [
  "mkdocstrings-python>=1.16.0",
  "mkdocs-material>=9.6.0",
  "mkdocs>=1.6.1",
]

[tool.cython-lint]
max-line-length = 140

[tool.ruff]
line-length = 140
indent-width = 4
target-version = "py312"
src = ["cydrogen", "tests"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
# selected ruff rules
# see https://docs.astral.sh/ruff/rules/
select = [
  "YTT",   # flake8-2020
  "ANN",   # annotations
  "ASYNC", # async
  "S",     # bandit
  "BLE",   # blind except
  "FBT",   # boolean trap
  "B",     # bugbear
  "A",     # builtins
  "COM",   # commas
  "C4",    # comprehensions
  "ISC",   # implicit str concatenation
  "ICN",   # import conventions
  "LOG",   # logging
  "G",     # logging format
  "INP",   # implicit namespace
  "PIE",   # pie
  "T20",   # print
  "PYI",   # pyi files
  "PT",    # pytest
  "Q",     # quotes
  "RSE",   # raises
  "RET",   # returns
  "SLF",   # private members
  "SIM",   # simplify
  "TC",    # type checking
  "ARG",   # unused arguments
  "PTH",   # use pathlib
  "I",     # unsorted imports
  "PERF",  # performance
  "E",     # pycodestyle
  "W",     # pycodestyle  TODO: "D",    # docstyle
  "F",     # pyflakes
  "PLE",   # pylint errors
  "PLR",   # pylint refactor
  "PLW",   # pylint warnings
  "UP",    # upgrades
  "FURB",  # refurbish
  "RUF",   # ruff
  "TRY",   # exceptions
]


ignore = [
  "S101",    # assert
  "PIE790",  # unnecessary ... in pyi files
  "PYI021",  # docstrings in pyi files
  "PYI029",  # __str__ in pyi files
  "PYI048",  # exactly one statement in pyi files 
  "PLR0913", # too many arguments
  "TRY300",
  "TRY003",
  "COM812",  # conflicts with ruff format
]

[tool.ruff.lint.per-file-ignores]
"tests/**.py" = [
  "ANN201",  # missing type annotations
  "PT011",   # pytest.raises too broad
  "E501",    # line too long
  "PLR2004", # magic values
]

"cydrogen/**.pyi" = [
  "E501", # line too long
]

"noxfile.py" = [
  "T201", # print statements 
]

"tools/**.py" = [
  "T201",    # print statements
  "PLR2004", # magic values
  "RUF001",  # ambiguous unicode chars
  "INP001",  # implicit namespace packages
  "PLR0912", # too many branches
]


[tool.pytest.ini_options]
console_output_style = "classic"
testpaths = "tests"
addopts = "--import-mode=importlib"
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"
#log_cli = true
#log_cli_level = "INFO"

[tool.meson-python.args]
setup = ["-Dbuildtype=minsize", "-Ddebug=false", "-Db_ndebug=true"]
