from typing import Self

class BaseKey:
    def __init__(self, b: bytes | None = None): ...
    def __str__(self) -> str: ...
    def eq(self, other: Self): ...
    def gen(cls) -> Self: ...
    def zero(cls) -> Self: ...
    def is_zero(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
