from collections.abc import Buffer
from typing import Self

class Context:
    def __init__(self, ctx: str | bytes | Self | Buffer | None = None): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
    @classmethod
    def empty(cls) -> Self: ...
