from collections.abc import Buffer

def hynit() -> None: ...
def random_u32() -> int: ...
def random_uniform(upper_bound: int) -> int: ...
def randomize_buffer(buf: Buffer) -> None: ...
def gen_random_buffer(size: int) -> bytes: ...
def shuffle_buffer(buf: Buffer) -> None: ...
