class CyException(Exception): ...
class EncryptException(CyException): ...
class DecryptException(CyException): ...
class DeriveException(CyException): ...
class SignException(CyException): ...
class VerifyException(CyException): ...
