name: CI

on:
  pull_request:
    branches: [develop,master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          python -m pip install --upgrade pip && pip install nox
      - name: install shellcheck
        run: |
          sudo apt-get install -y shellcheck
      - name: install actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo mv actionlint /usr/local/bin

      - name: run linters
        run: |
          nox -s lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]   
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          python -m pip install --upgrade pip && pip install nox
      - name: install build dependencies
        run: |
          sudo apt-get install -y build-essential binutils
      - name: build cydrogen
        run: |
          nox -s build-${{matrix.python-version}}
      - name: upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cydrogen-${{matrix.python-version}}-build
          path: dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
          check-latest: true
      - name: install nox and pytest
        run: |
          python -m pip install --upgrade pip && pip install nox pytest
      - name: download wheel from artifacts
        uses: actions/download-artifact@v4
        with:
          name: cydrogen-${{matrix.python-version}}-build
          path: dist
      - name: install cydrogen
        run: |
          pip install dist/*.whl
      - name: run tests
        run: |
          pytest
