name: CI

on:
  pull_request:
    branches: [develop,master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          python -m pip install --upgrade pip && pip install nox
      - name: run linters
        run: |
          nox -s lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]   
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          python -m pip install --upgrade pip && pip install nox
      - name: install build dependencies
        run: |
          sudo apt-get install -y build-essential
      - name: build cydrogen
        run: |
          nox -s build-${{matrix.python-version}}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          python -m pip install --upgrade pip && pip install nox
      - name: install build dependencies
        run: |
          sudo apt-get install -y build-essential
      - name: run tests
        run: |
          nox -s test-${{matrix.python-version}}

