name: CI

on:
  pull_request:
    branches: [develop,master]

permissions:
  contents: read
  actions: read

jobs:

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false
          persist-credentials: false
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install nox
      - name: install shellcheck
        run: |
          sudo apt-get install -y shellcheck
      - name: install actionlint
        run: |
          set -euo pipefail
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          sudo mv actionlint /usr/local/bin
      - name: install typos
        run: |
          set -euo pipefail
          curl -sSL -o typos.tar.gz https://github.com/crate-ci/typos/releases/download/v1.32.0/typos-v1.32.0-x86_64-unknown-linux-musl.tar.gz
          tar -xvzf typos.tar.gz ./typos
          rm typos.tar.gz
          sudo mv typos /usr/local/bin
      - name: run linters
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for zizmor
        run: |
          nox -s lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]   
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
          check-latest: true
      - name: install nox
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install nox
      - name: install build dependencies
        run: |
          sudo apt-get install -y build-essential binutils
      - name: build cydrogen
        run: |
          nox -s build-${{matrix.python-version}}
      - name: upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cydrogen-${{matrix.python-version}}-build
          path: dist/*.whl

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
          check-latest: true
      - name: install nox and pytest
        run: |
          python -m pip install --upgrade pip && pip install nox pytest
      - name: download wheel from artifacts
        uses: actions/download-artifact@v4
        with:
          name: cydrogen-${{matrix.python-version}}-build
          path: dist
      - name: install cydrogen
        run: |
          pip install dist/*.whl
      - name: run tests
        run: |
          pytest
