name: CI

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: ./.github/workflows/_ci.yaml
