name: CI

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  ci:
    uses: ./.github/workflows/_ci.yaml
