name: CI master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/**

permissions: {}

jobs:
  ci:
    uses: ./.github/workflows/_ci.yaml
    permissions:
      contents: read
      actions: read
      pull-requests: write
  build_wheels:
    needs: ci
    uses: ./.github/workflows/wheels.yaml
    permissions:
      contents: read
      actions: read
