name: Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  # Cancel previous workflows on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:

  ci:
    uses: ./.github/workflows/_ci.yaml

  build_wheels:
    needs: ci
    uses: ./.github/workflows/wheels.yaml

  publish:
    if: github.repository == 'stephane-martin/cydrogen' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: [ci, build_wheels]
    runs-on: ubuntu-22.04
    environment: publish
    defaults:
      run:
        shell: bash
    permissions:
      contents: write # for softprops/action-gh-release to create GitHub release
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      attestations: write # for GitHub attestations
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.13"
          check-latest: true
          # Important! No caching for wheel build to avoid cache poisoning
      - name: install nox
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install nox
      - name: build sdist
        run: |
          nox -s "build_sdist-3.13"
      - name: gather wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./dist
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
