name: Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  # Cancel previous workflows on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:

  ci:
    uses: ./.github/workflows/_ci.yaml

  build_wheels:
    needs: ci
    uses: ./.github/workflows/wheels.yaml

  publish:
    if: github.repository == 'stephane-martin/cydrogen' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: [ci, build_wheels]
    runs-on: ubuntu-22.04
    environment: publish
    defaults:
      run:
        shell: bash
    permissions:
      contents: write # for softprops/action-gh-release to create GitHub release
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      attestations: write # for GitHub attestations
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true
          # Important! No caching for wheel build to avoid cache poisoning
      - name: Install nox
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install nox
      - name: build sdist
        run: |
          nox -s "build_sdist-3.13"
      - name: Gather wheels   # wheels were built in the build_wheels job and uploaded as artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./dist
      - name: Generate attestations for Github
        uses: actions/attest-build-provenance@v2.3.0
        with:
          subject-path: 'dist/*'
      - name: Publish to PyPI # this also generates attestations for PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          packages_dir: ./dist
      - name: Create Github release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          body_path: "${{ github.workspace }}/last_release_changes.md"
          repository: stephane-martin/cydrogen
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          # target_commitish: we don't need it as we are using an existing tag
          files: |
            ./dist/*.tar.gz
            ./dist/*.whl
