name: Build wheels for supported environments

on:
  workflow_call:
  workflow_dispatch:

env:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_ENVIRONMENT: "PIP_PREFER_BINARY=1" 
  CIBW_BUILD_FRONTEND: "build"
  CIBW_TEST_COMMAND: "pytest {project}"
  CIBW_TEST_GROUPS: "test"
  CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
  CIBW_MANYLINUX_AARCH64_IMAGE: "manylinux_2_28"
  CIBW_SKIP: "*-musllinux_*"

permissions:
  contents: read

jobs:
  build_wheels:
    strategy:
      matrix:
        include:
          - runner: "ubuntu-22.04"
            cibw_build: "cp{312,313}-manylinux_x86_64"
            cibw_archs: "x86_64"
            os: "linux"
          - runner: "ubuntu-22.04-arm"
            cibw_build: "cp{312,313}-manylinux_aarch64"
            cibw_archs: "aarch64"
            os: "linux"
          - runner: "windows-2025"
            cibw_build: "cp{312,313}-win_amd64"
            cibw_archs: "AMD64"
            os: "windows"
          - runner: "macos-15"
            cibw_build: "cp{312,313}-macosx_arm64"
            cibw_archs: "arm64"
            os: "macos"
          - runner: "macos-13"
            cibw_build: "cp{312,313}-macosx_x86_64"
            cibw_archs: "x86_64"
            os: "macos"
    name: "Build wheels for ${{ matrix.os }} ${{ matrix.cibw_archs }}"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: Build wheels
        uses: pypa/cibuildwheel@faf86a6ed7efa889faf6996aa23820831055001a # v2.23.3
        env:
          CIBW_BUILD: "${{ matrix.cibw_build }}"
          CIBW_ARCHS: "${{ matrix.cibw_archs }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "wheels-${{ matrix.os }}-${{ matrix.cibw_archs }}"
          path: ./wheelhouse/*.whl
