name: Build wheels for supported environments

on:
  workflow_call:
  workflow_dispatch:

env:
  CIBW_BUILD_VERBOSITY: 1
  CIBW_ENVIRONMENT: "PIP_PREFER_BINARY=1" 
  CIBW_BUILD_FRONTEND: "build"
  CIBW_TEST_COMMAND: "pytest {project}"
  CIBW_TEST_GROUPS: "test"
  CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
  CIBW_MANYLINUX_AARCH64_IMAGE: "manylinux_2_28"
  CIBW_SKIP: "*-musllinux_*"

permissions:
  contents: read

jobs:
  build_linux_x64_wheels:
    name: "Build linux x86_64 wheels"
    runs-on: "ubuntu-22.04"
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BUILD: "cp{312,313}-manylinux_x86_64"
          CIBW_ARCHS_LINUX: "x86_64"
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: ./wheelhouse/*.whl

  build_linux_arm64_wheels:
    name: "Build linux aarch64 wheels"
    runs-on: "ubuntu-22.04-arm"
    steps:
      - name: checkout cydrogen repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          persist-credentials: false
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BUILD: "cp{312,313}-manylinux_aarch64"
          CIBW_ARCHS_LINUX: "aarch64"
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-aarch64
          path: ./wheelhouse/*.whl
